# Generated by Django 5.0.6 on 2024-06-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_videocomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
